name: Test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    name: test-${{ matrix.deno }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [stable, canary]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{matrix.deno == 'canary' && 'canary' || ''}}

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Check
        run: deno check *.ts

      - name: Test
        run: deno test --check

      - name: Publish Test
        run: deno publish --dry-run
